### ISSUE TITLE
External encrypt

### ISSUE THREAD

**Issue by xorgxx** [NAYZO/NzoUrlEncryptorBundle#25]
Hi 
i'm trying to "encrypt" from external application and to decrypt with your bundle. 

my fonction is this  : 
```
sData = Crypte("sMessage", "13EF78894A6A3D2EFC2900E8",crypteSécurisé,encodeBASE64)
**crypteSécurisé = type RINJDAEL 128 bits ( algorithme RC5 sur 128 bits )

```
so i put in config.yml : 
```
nzo_url_encryptor:
    secret_key: 13EF78894A6A3D2EFC2900E8        # optional, max length of 100 characters.
    secret_iv:  F572EKA76WA3B8544L9JJ389        # optional, max length of 100 characters.
    cipher_algorithm:  'aes-128-ctr'            # optional, default: 'aes-256-ctr'
```

i get this in debug mode : 
```
            $data = $request->request->get("data");      >>>>>>>> 8ww6cBNzcld5Thry0xnuDA==
            $data = $this->encryptor->decrypt($data);   >>>>>>>> &M�g
```

can you help to find my problem ?
